USE [master]
GO

/****** Object:  Database [Demo0]    Script Date: 3/13/2018 8:58:25 AM ******/
CREATE DATABASE [Demo0]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo0', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo0.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo0_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo0_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo0] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo0].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo0] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo0] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo0] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo0] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo0] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo0] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo0] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo0] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo0] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo0] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo0] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo0] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo0] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo0] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo0] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo0] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo0] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo0] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo0] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo0] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo0] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo0] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo0] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo0] SET  MULTI_USER 
GO

ALTER DATABASE [Demo0] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo0] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo0] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo0] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo0] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo0] SET QUERY_STORE = OFF
GO

USE [Demo0]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo0] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo1]    Script Date: 3/13/2018 8:58:33 AM ******/
CREATE DATABASE [Demo1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo1', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo1_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo1] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo1] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo1] SET  MULTI_USER 
GO

ALTER DATABASE [Demo1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo1] SET QUERY_STORE = OFF
GO

USE [Demo1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo1] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo2]    Script Date: 3/13/2018 8:58:38 AM ******/
CREATE DATABASE [Demo2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo2', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo2_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo2] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo2] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo2] SET  MULTI_USER 
GO

ALTER DATABASE [Demo2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo2] SET QUERY_STORE = OFF
GO

USE [Demo2]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo2] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo3]    Script Date: 3/13/2018 8:58:42 AM ******/
CREATE DATABASE [Demo3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo3', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo3_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo3] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo3] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo3] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo3] SET  MULTI_USER 
GO

ALTER DATABASE [Demo3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo3] SET QUERY_STORE = OFF
GO

USE [Demo3]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo3] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo4]    Script Date: 3/13/2018 8:58:46 AM ******/
CREATE DATABASE [Demo4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo4', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo4_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo4] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo4] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo4] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo4] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo4] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo4] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo4] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo4] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo4] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo4] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo4] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo4] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo4] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo4] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo4] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo4] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo4] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo4] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo4] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo4] SET  MULTI_USER 
GO

ALTER DATABASE [Demo4] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo4] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo4] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo4] SET QUERY_STORE = OFF
GO

USE [Demo4]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo4] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo5]    Script Date: 3/13/2018 8:58:51 AM ******/
CREATE DATABASE [Demo5]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo5', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo5_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo5] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo5].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo5] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo5] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo5] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo5] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo5] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo5] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo5] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo5] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo5] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo5] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo5] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo5] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo5] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo5] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo5] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo5] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo5] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo5] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo5] SET  MULTI_USER 
GO

ALTER DATABASE [Demo5] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo5] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo5] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo5] SET QUERY_STORE = OFF
GO

USE [Demo5]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo5] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo6]    Script Date: 3/13/2018 8:58:56 AM ******/
CREATE DATABASE [Demo6]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo6', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo6.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo6_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo6_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo6] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo6].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo6] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo6] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo6] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo6] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo6] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo6] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo6] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo6] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo6] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo6] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo6] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo6] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo6] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo6] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo6] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo6] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo6] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo6] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo6] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo6] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo6] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo6] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo6] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo6] SET  MULTI_USER 
GO

ALTER DATABASE [Demo6] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo6] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo6] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo6] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo6] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo6] SET QUERY_STORE = OFF
GO

USE [Demo6]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo6] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo7]    Script Date: 3/13/2018 8:59:00 AM ******/
CREATE DATABASE [Demo7]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo7', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo7.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo7_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo7_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo7] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo7].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo7] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo7] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo7] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo7] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo7] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo7] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo7] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo7] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo7] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo7] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo7] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo7] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo7] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo7] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo7] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo7] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo7] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo7] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo7] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo7] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo7] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo7] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo7] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo7] SET  MULTI_USER 
GO

ALTER DATABASE [Demo7] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo7] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo7] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo7] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo7] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo7] SET QUERY_STORE = OFF
GO

USE [Demo7]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo7] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo8]    Script Date: 3/13/2018 8:59:05 AM ******/
CREATE DATABASE [Demo8]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo8', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo8.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo8_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo8_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo8] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo8].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo8] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo8] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo8] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo8] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo8] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo8] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo8] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo8] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo8] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo8] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo8] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo8] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo8] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo8] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo8] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo8] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo8] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo8] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo8] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo8] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo8] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo8] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo8] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo8] SET  MULTI_USER 
GO

ALTER DATABASE [Demo8] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo8] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo8] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo8] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo8] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo8] SET QUERY_STORE = OFF
GO

USE [Demo8]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo8] SET  READ_WRITE 
GO

USE [master]
GO

/****** Object:  Database [Demo9]    Script Date: 3/13/2018 8:59:09 AM ******/
CREATE DATABASE [Demo9]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo9', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLData\USERDATA\Demo9.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo9_log', FILENAME = N'C:\Dev\sqlserverbuilds-SQL1\M\SQLLog\USERLOG\Demo9_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Demo9] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Demo9].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Demo9] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Demo9] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Demo9] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Demo9] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Demo9] SET ARITHABORT OFF 
GO

ALTER DATABASE [Demo9] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Demo9] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Demo9] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Demo9] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Demo9] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Demo9] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Demo9] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Demo9] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Demo9] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Demo9] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Demo9] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Demo9] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Demo9] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Demo9] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Demo9] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Demo9] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Demo9] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Demo9] SET RECOVERY FULL 
GO

ALTER DATABASE [Demo9] SET  MULTI_USER 
GO

ALTER DATABASE [Demo9] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Demo9] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Demo9] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Demo9] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Demo9] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Demo9] SET QUERY_STORE = OFF
GO

USE [Demo9]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Demo9] SET  READ_WRITE 
GO

